### ISSUE TITLE
Add CodeQL code analysis

### ISSUE THREAD

**Issue by vishnuravi** [StanfordBDHG/PediatricAppleWatchStudy#38]
### Problem

The project currently does not have any automated vulnerability scanning, which is recommended by Stanford IT.

### Solution

Enable CodeQL on this repository for vulnerability scanning.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
Added some foundations for this in Spezi (https://github.com/StanfordSpezi/Spezi/pull/70) and in the .github repo: https://github.com/StanfordSpezi/Spezi/pull/70
