### ISSUE TITLE
Migrate to Spezi 0.7.0

### ISSUE THREAD

**Issue by vishnuravi** [StanfordBDHG/PediatricAppleWatchStudy#40]
### Problem

CardinalKit has been relaunched as Spezi, which has a new structure with updated modules separated out into independent swift packages. Many bug fixes have also been made.

### Solution

The PAWS application should be updated to the new Spezi framework, by following the structure of the new Spezi Template Application that can be found at https://github.com/StanfordSpezi/SpeziTemplateApplication

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
We are holding off on this migration until all the modules are updated for Spezi 0.7.0. cc: @PSchmiedmayer

**Comment by vishnuravi** [comment]
All modules have been updated, as well as the template application. We can proceed with this migration.

**Comment by PSchmiedmayer** [comment]
A large code diff and some steps toward Spezi 1.0 can be found here #42. Still a WIP.
