### ISSUE TITLE
GitHub Action when Forking

### ISSUE THREAD

**Issue by gottliebtj** [StanfordBDHG/PediatricAppleWatchStudy#60]
### Description

When i fork the repo and run the workflows the Build and Test job seems to fail 
<img width="308" alt="Screenshot 2024-05-02 at 1 53 01 PM" src="https://github.com/StanfordBDHG/PediatricAppleWatchStudy/assets/37161605/c508881f-50db-4843-a217-f58d16c8add6">

### Reproduction

fork the repo add secrets and run 

### Expected behavior

should pass.

### Additional context

Please reach out and we can walk through my setup to see if ive correctly encoded everything to base64 and set up secrets and workflows properly. tgottlieb6@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
@gottliebtj Can you share a more detailed description why the build is failing? What is the error message and the output that you get in the failing build?

**Comment by PSchmiedmayer** [comment]
Closed due to inactivity. @gottliebtj please let us know if this is still an issue that you are working on.
